name: "ChatGPT Integration"
description: "This action integrates ChatGPT into your CI."
branding:
  icon: activity
  color: green

inputs:
  number:
    description: "ID of Pull Request or Issue"
    required: true
  sessionToken:
    description: "Your ChatGPT session token."
    required: true
  mode:
    description: "Mode"
    required: true
    default: "pr"
  split:
    description: "Should I split the prompt and how to split it?"
    required: true
    default: "yolo"
  lang:
    description: "Write a review in {lang}. ex Japanese"
    default: ""
outputs:
  comment:
    description: "The comment from chatgpt."
runs:
  using: "node16"
  main: "dist/index.js"
